<?php

/**
 * @file
 * Contains hook implementations for YAML Form Clear module.
 */

use Drupal\yamlform_clear\YamlFormSubmissionNullStorage;

/**
 * Implements hook_entity_type_alter().
 *
 * @param \Drupal\Core\Entity\EntityTypeInterface[] $entity_types
 */
function yamlform_clear_entity_type_alter(array &$entity_types) {
  $handlers = $entity_types['yamlform_submission']->getHandlerClasses();
  $handlers['storage'] = YamlFormSubmissionNullStorage::class;
  // Views integration depends on messages being stored in the database.
  unset($handlers['views_data']);
  $entity_types['yamlform_submission']->set('handlers', $handlers);
}
